### ISSUE TITLE
Nūn and nūn ghunna usage notes

### ISSUE THREAD

**Issue by moyogo** [r12a/r12a.github.io#1]
The notes for U+0646 and U+06BA usage in Urdu seem to be incorrect.

https://github.com/r12a/r12a.github.io/blob/master/scripts/arabic/block.html#L1373

> <p><span class="title">Urdu</span> consonant, <span class='name'>nūn</span> <span class='ipa'>nuːn</span></p>
> <p><span class="ipa">n</span> </p><p>Looks like: <span lang="ur" dir="rtl">ننن ن</span></p>
> <p>Within a word this looks exactly the same as U+06BA ARABIC LETTER NOON GHUNNA, which is used for nasalization of vowels, eg. <span class="ex" lang="ur" dir="rtl">ٹاںگ</span> <span class="ipa">ʈɑː̃g</span> (<span class="meaning">leg</span>).</p>

https://github.com/r12a/r12a.github.io/blob/master/scripts/arabic/block.html#L2196

> <p><span class="title">Urdu</span> nasalisation indicator, <span class='name'>nun ghunna</span> <span class="ipa">nuːn ɣunna</span>.</p>
> <p>Looks like: <span lang="ur" dir="rtl">ںںں ں</span></p>
> <p>Indicates that the preceding vowel is nasalised.</p>
> <p>At the end of a word, an undotted form is used, eg. <span class="ex" lang="ur" dir="rtl">ماں</span> <span class="ipa">mãː</span>, <span class="meaning">mother</span>, <span class="ex" lang="ur" dir="rtl">کروں</span> <span class="ipa">karũː</span>, <span class="meaning">I may do</span>.  </p>
> <p>Nasalization <em>within</em> a word uses a form with a dot that looks just like the letter  <span lang="ur" dir="rtl">ن</span> 0646 ARABIC LETTER NOON, eg. <span class="ex" lang="ur" dir="rtl">ٹاںگ</span> <span class="ipa">tãːg</span> <span class="meaning">leg</span>.</p>

These disagree with [L2/12-381](http://www.unicode.org/L2/L2012/12381-dotless-noon.pdf).
In particular: 
> Urdu speakers think of Noon Ghunna as they think of Yeh Barree: a subclass of another letter,
whose differences are only visible in final and isolated forms. While a final or islated Noon
Ghunna is most commonly written as a dotless Noon, it’s also sometimes written as a dotted
Noon with a ghunna mark (U+0658) above it. A initial or medial “semantic” Noon Ghunna is
also commonly written with a normal Noon (U+0646), with a Ghunna mark (U+0658). 

Windows fonts have a dot on the initial and medial dotless nun while other platforms’ fonts don’t. L2/12-381 proposed to document the initial and medial forms should be dotless. It also proposed alternatives resolutions but these were not chosen.

The Unicode chart indicate in U+06BA’s note (since Unicode 6.3):
> dotless in all four contextual forms

For scale:
- ٹانگ &lrm; <0679 0627 0646 06AF> has [4,310 reported results on Bing](https://www.bing.com/search?q=%22%D9%B9%D8%A7%D9%86%DA%AF%22) and [315,000 reported results on Google](https://encrypted.google.com/search?hl=en&q="ٹانگ")
- ٹاںگ &lrm; <0679 0627 06BA 06AF> has [10 results on Bing](https://www.bing.com/search?q="ٹاںگ") and  [2,660 reported but actually 20 results on Google](https://encrypted.google.com/search?hl=en&q="ٹاںگ"&start=10)

So, the Urdu usage notes should indicate that the Urdu nasalisation nūn is represented with a dotted nūn U+0646 in initial and medial forms and dotless nūn ghunna U+06BA in final or isolated forms, or optionally with a dotted nūn combined with 0658 ARABIC MARK NOON GHUNNA in initial and media forms or all positions. The pronunciations should be the same for the example (tãːg vs. ʈɑː̃g).

**Comment by moyogo** [comment]
See also http://www.unicode.org/versions/Unicode8.0.0/ch09.pdf#page=26 page 26-27.
> Noon Ghunna. The letter noon ghunna is used to mark nasalized vowels at the ends of
words and some morphemes in Urdu, Balochi, and other languages of Southern Asia. It is
represented by U+06BA arabic letter noon ghunna. The noon ghunna has the shape of
a dotless noon and typically appears only in final and isolated contexts in these languages.
In the middle of words and morphemes, the normal noon, U+0646 arabic letter noon, is used instead. To avoid ambiguity, sometimes a special mark, U+0658 arabic mark
noon ghunna, is added to the dotted noon to indicate nasalization.

> U+06BA arabic letter noon ghunna is also used as a dotless noon for the noon skeleton
in all four of its contextual forms. As such, it is used in representation of early Arabic and
Koranic Arabic texts. Rendering systems should display U+06BA as a dual-joining letter,
with all four contextual forms shown dotless, regardless of the language of the text.

> Advanced text entry applications for Urdu, Balochi, and other languages using noon
ghunna may include specialized logic for its handling. For example, they might detect midword
usage of the noon ghunna key and emit the regular dotted noon character (U+0646)
instead, as appropriate for spelling in that context.

**Comment by r12a** [comment]
@moyogo many thanks for the pointers.  Hopefully it's looking better now.

**Comment by moyogo** [comment]
LGTM now.
Thanks!
