### ISSUE TITLE
Missing Gujarati Picker

### ISSUE THREAD

**Issue by padhia** [r12a/r12a.github.io#10]
Hello,

From https://r12a.github.io/pickers/ when I click on `Gujarati Picker`, it links to http://rishida.net/scripts/pickers/gujarati/ which redirects to a non-working link http://r12a.github.io/pickers/gujarati/.

Would it be possible to provide a picker for the Gujarati script?

Thanks.

BTW, very useful set of apps you have here. Thank you for that.

**Comment by r12a** [comment]
Moved to https://github.com/r12a/pickers/issues/5

**Comment by r12a** [comment]
@padhia sorry it took so long, but finally a Gujarati picker is now available at https://r12a.github.io/pickers/gujarati/

hope that helps

**Comment by padhia** [comment]
Thank you very much for bringing it back!
