### ISSUE TITLE
An Urdu reference needs update due to the content reocation

### ISSUE THREAD

**Issue by ibnesayeed** [r12a/r12a.github.io#11]
Dr. Kamal Abdali's site hosted on http://patriot.net/~abdali/ has been relocated to http://geomete.com/ after several years. Corresponding references on Urdu pages need to be updated.

**Comment by ibnesayeed** [comment]
Fixed by PR #12

**Comment by r12a** [comment]
Thanks for providing this information, and for the PR.  I fixed locally and pushed, since i wanted to remove the duplicate file at /scripts/urdu/.  Should be ok now (at /scripts/arabic/urdu).
