### ISSUE TITLE
http://r12a.github.io/apps/conversion/ is not working anymore

### ISSUE THREAD

**Issue by zhenjie** [r12a/r12a.github.io#13]
Hey thanks for the great effort on providing this service: http://r12a.github.io/apps/conversion/

Looks like it's not working after recent updates. Can someone help fixing it I would try to fix it on my own if I have time too.

Thank you so much!

**Comment by r12a** [comment]
Can you provide more information about how this is not working?  It seems ok for me.

**Comment by zhenjie** [comment]
Hm, interesting, looks like it's working fine now.
