### ISSUE TITLE
Missing space separator between first two characters in some strings

### ISSUE THREAD

**Issue by mumbleskates** [r12a/r12a.github.io#15]
For example: Putting "👨‍❤️‍💋‍👨" in the green box and hitting 'convert' results in incorrect output in the following boxes:

* U+hex
* 0x...
* Hexadecimal
* Decimal

In all these outputs, the issue is similar: there is no space (zero width or otherwise) between the first and second characters in the output code.

**Comment by r12a** [comment]
Moved to https://github.com/r12a/app-conversion/issues/3
