### ISSUE TITLE
"Old Malay" is misleading as some of them are still in use

### ISSUE THREAD

**Issue by MuhdNurHidayat** [r12a/r12a.github.io#22]
I noticed that "old Malay" is mentioned for a few letters on [Arabic block page](https://r12a.github.io/scripts/arabic/block), even though some of the letters marked as "old Malay" are still in use in modern-day Malay language.

One of the misleading examples is the letter NGA:
![firefox_2018-07-01_04-26-10](https://user-images.githubusercontent.com/12217018/42128825-eefca22e-7ce6-11e8-8b4e-75304b376d60.png)
NGA is in fact used in the conjunction word "يڠ" (yang) meaning "which" or "that" and it's one of the words commonly used in modern Malay.

Letters that is still in use in modern Malay but marked as old Malay includes:
- ڠ (NGA) - U+06A0 `ARABIC LETTER AIN WITH THREE DOTS ABOVE`
- ڬ (GA) - U+06AC `ARABIC LETTER KAF WITH DOT ABOVE` (usable, but usually use ݢ)
- ڽ (NYA) - U+06BD `ARABIC LETTER NOON WITH THREE DOTS ABOVE`
- ݢ (GA) - U+0762 `ARABIC LETTER KEHEH WITH DOT ABOVE` (favoured)

*Letters that we never actually saw or knew to be part of Malay but marked as old Malay includes ڭ and ۑ ... maybe those are indeed old Malay since we never even knew about them.*

-----
In case you don't know. Malay in Arabic script (known as Jawi script) is generally still in use, and it is accepted in Malay language national examination in Malaysia, besides holding status as co-official writing system in Brunei. More on [Wikipedia](https://en.wikipedia.org/wiki/Jawi_alphabet).

There's a declaration in Malay (Arabic script) that could be read at https://unicode.org/udhr/d/udhr_mly_arab.html and the respective character count is at https://unicode.org/udhr/d/udhr_mly_arab.charcount

I got some pictures in case you want to see it in use in real life:
- [This](https://drive.google.com/file/d/1hSn9Gqgb1UMj3jlbu3wFBicma96DUp-g/view?usp=sharing) is the front and back cover page of one of the national examination paper that is written in Malay using both Arabic and Latin script.
- [This](https://drive.google.com/file/d/1yIUTtiFYe9rW9gH0S7iGFDqnGe-t68RE/view?usp=sharing) is the Malay language paper from 2017 Malaysian national examination, and even though the question is in Latin script, the last point in the instruction has explicitly wrote that students can answer the question in either Latin or Arabic script.
- [This](https://drive.google.com/file/d/1LU33WaLkbOc_-bFSgadJyBk9Iq7qek-l/view?usp=sharing) is the Islamic Education textbook in Malaysia, the official textbook of this subject for all schools are written only in Malay in Arabic script.
- In the Malaysian state of Selangor (among others), all property and road signboards need to be written in both Arabic script and Latin script. I have some pictures in Selangor that shows such bi-script signs like [this hospital](https://drive.google.com/file/d/1wHi6Z7Ctw05kdzK6gEyLDeK0z23Bfxh9/view?usp=sharing), [this road](https://drive.google.com/file/d/1oL76ddXxkv9RQnKRyjTPKv35TwjxJGr3/view?usp=sharing), and [this other road](https://drive.google.com/file/d/1Sna403mupLIyluqoHZSJPUsgYigSA1um/view?usp=sharing).

**Comment by r12a** [comment]
@MuhdNurHidayat thank you for your comments, and useful links.

The references to Old Malay that you referred to are taken from and old version of the data associated with the Unicode Standard.  I'll refresh that data. because I noticed that in the latest version of the standard several references to Old Malay appear to have been replaced by references to Jawi. eg. https://r12a.github.io/uniview/?char=06A0.

I just need to find some time to make those changes.

**Comment by r12a** [comment]
The description information taken from Unicode on the [Arabic block page](https://r12a.github.io/scripts/arabic/block) has now been updated to version 11, which replaces 'Old Malay' with 'Jawi' in several locations.

The page also now links to the character usage information for characters that don't have notes, eg. 06A0 has a link to the Malay data now.

So i think we can now close this.  Reopen if there are still problems related to the above bugs.
