### ISSUE TITLE
RSS for Blog

### ISSUE THREAD

**Issue by Almad** [r12a/r12a.github.io#26]
Thanks so much for the site! I keep recommending it to engineers heavily. 

I visited after few years and realized there are few new posts I've missed. I think it would be great if there would be RSS for the blog. It's an article every year or two, but I don't want to miss it!

**Comment by r12a** [comment]
@Almad all my stuff is now announced on the @r12a Twitter feed, so you should get what you need there.

**Comment by Almad** [comment]
Thanks!
