### ISSUE TITLE
Javanese script (java) is used in Madurese language (mad)

### ISSUE THREAD

**Issue by bennylin** [r12a/r12a.github.io#29]
https://r12a.github.io/scripts/java/

The Javanese script is used for the following languages. Information is from ScriptSource and Ethnologue.

    Balinese [ban]
    [Javanese [jv]](https://r12a.github.io/scripts/java/jv.html)
    Osing [osi]
    Sundanese [sun]
    Tengger [tes]
    Total: 5

The list is incomplete. It is used in the past, and in the current Madurese language as well. See mad.wikipedia.org/ and https://commons.wikimedia.org/wiki/Category:Javanese_script_in_Madura

**Comment by r12a** [comment]
Added. Thanks.
