### ISSUE TITLE
Add superscript glottal stop (representing glottalization) to the IPA character app keyboard

### ISSUE THREAD

**Issue by GiggyMantis** [r12a/r12a.github.io#32]
Hello! This is a pretty simple fix, it's just a character missing from the set of superscript characters on this keyboard. Right now there is `ʰ ˭ ⁿ ˡ ˤ ˠ ʲ ʷ` but notably no `ˀ`.

**Comment by r12a** [comment]
Coincidentally, i was missing that character too, recently.  I made some time to add it (to all 3 ipa pickers).  Thanks for the nudge.
