### ISSUE TITLE
[BUG] Incorrect ordering of the superscript modifier characters on some IPA apps

### ISSUE THREAD

**Issue by GiggyMantis** [r12a/r12a.github.io#33]
See:
![image](https://github.com/user-attachments/assets/380366de-b08d-460b-87e1-7f65d845de9e)

The indication is that %+1 is ʰ, %+2 is ˭, etc.
The actual order is `ʼʰ˭ⁿˡʷʲˠˤˀ`, compared to `ʰ˭ʼⁿˡʷʲˤˠˀ`

**Comment by GiggyMantis** [comment]
I wish I knew enough about websites to fix this for you and pull request it, I don't like bothering you with all these simple requests.

**Comment by r12a** [comment]
Thanks for mentioning this oversight.  Should be fixed now. Let me know if not.
