### ISSUE TITLE
Rust-style escapes

### ISSUE THREAD

**Issue by hsivonen** [r12a/r12a.github.io#7]
Lately, I've been using the [Unicode converter](https://r12a.github.io/apps/conversion/) when working on Rust code. It would be nice if the converter supported [Rust-style escapes](https://doc.rust-lang.org/reference.html#character-escapes) directly to support this use case better.

**Comment by r12a** [comment]
@hsivonen it looks like it would be possible to escape, say, U+0009 in Rust as \x79, \u{79} or \t.  Should one be able to specify to which to produce in output?  Also, can i assume that visible ASCII characters don't need escaping?

**Comment by hsivonen** [comment]
I was mainly thinking of non-ASCII, so `\u{2603}` for BMP and `\u{1F4A9}`.

It seems that the converter currently doesn't escape visible ASCII for the "JavaScript" target, so not escaping visible ASCII for Rust makes sense.

I suppose `\n`, `\r`, `\t` and `\\` are preferable over the numeric options. (BTW, the "JavaScript" target would benefit, too, from producing escapes for these.)

For invisible ASCII, I'd prefer `\x1B` over `\u{001B}`, because the former is shorter. Having an option to control which of these to use would probably be an overkill.

**Comment by r12a** [comment]
@hsivonen that all fits with what i was expecting. Please try this out and let me know if you're happy with it. If you are, i'll formally release in the normal location.
http://r12a.github.io/apps/conversiontest/

**Comment by hsivonen** [comment]
Thank you! I seems to work very well.

Minor nit: When converting towards Rust, astral characters use lowercase a…f while Rust BMP, Rust invisible ASCII and all other hex outputs in the app use upper case A…F. It would be more consistent to use upper case A…F for astral Rust output, too.

**Comment by r12a** [comment]
Done. Switched back to the normal location.
Reopen this issue if you spot a problem.

**Comment by hsivonen** [comment]
Thank you!
