### ISSUE TITLE
Recommend more Mongolian fonts

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [r12a/r12a.github.io#9]
I want to recommend some Mongolian fonts to you if you want to expand the article [Notes on Mongolian variant forms](https://r12a.github.io/scripts/mongolian/variants).

* Oyun fonts by Inner Mongolian University
- http://oyun.mglip.com/mongolfont/index.aspx
* Abkai fonts by abkai.net
- http://abkai.net/core/en/manchu/manchu-fonts/

BTW I found a people [reported](https://tinyurl.com/jodts8z) some glyph behaviours may not yet be available in currently released versions of Mongolian Baiti, so I decided to sand the latest version of Mongolian Baiti to you, which copied from my computer.

[Mongolian Baiti 5.51.zip](https://github.com/r12a/r12a.github.io/files/461958/Mongolian.Baiti.5.51.zip)

**Comment by r12a** [comment]
> BTW I found a people reported some glyph behaviours may not yet be available in currently released versions of Mongolian Baiti

thanks. The behaviour described in the baiti column may still be for versions later than 5.1, since i was getting the information a person developing the font, but i will update the information in the tables to represent 5.1.

**Comment by r12a** [comment]
Table updated to represent MB 5.51. See diff at https://github.com/r12a/r12a.github.io/commit/60e674fa9cb65a14d1b4fe585d33e27348c928a8

**Comment by r12a** [comment]
@KrasnayaPloshchad would you like to participate in the discussion on the mailing list at https://lists.w3.org/Archives/Public/public-i18n-mongolian/ ?  If so, please subscribe using the link on that page, or contact me with your email address and i'll add you.

**Comment by KrasnayaPloshchad** [comment]
Sorry, I know vety a little about Mongolian an related technologies, I cannot participate in this discussion. But I recomment you to invite authors of Oyun and Abkai fonts to participate in, they are all experienced on this.

**Comment by r12a** [comment]
ok, thanks
